apiVersion: apps/v1
kind: Deployment
metadata:
  name: fisherman-app
  namespace: drawing  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fisherman-app
  template:
    metadata:
      labels:
        app: fisherman-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8000'         
    spec:
      containers:
      - name: fisherman-app
        image: fisherman-app:v4
        ports:
        - containerPort: 8000 # Port pour les métriques Prometheus
        - containerPort: 5000 # Port pour l'API Flask
        imagePullPolicy: Never
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
---
apiVersion: v1
kind: Service
metadata:
  name: fisherman-app-api
  namespace: drawing  
spec:
  selector:
    app: fisherman-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fisherman-app-ingress
  namespace: drawing
spec:
  ingressClassName: contour
  rules:
  - host: fisherman.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fisherman-app-api
            port:
              number: 80

